services:
  backend:
    build: ./backend
    container_name: yaml-parser-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      # Mount the project directory for analysis - change HOST_PROJECT_PATH to your desired directory
      # Bu dizini mount ediyoruz. project folder bu dizinde olmalı. 
      - E:\ecommerce-platform:/app/projects
      # Remove this line that's causing the error:
      # - ./yaml_parser.py:/app/yaml_parser.py
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      # Container path where projects will be mounted
      - CONTAINER_PROJECT_PATH=/app/projects
    networks:
      - yaml-parser-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: yaml-parser-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yaml-parser-network
    restart: unless-stopped

networks:
  yaml-parser-network:
    driver: bridge

volumes:
  uploads:
    driver: local