services:
  backend:
    image: bdutucu/yaml-parser-backend:latest
    container_name: yaml-parser-backend-prod
    ports:
      - "5000:5000"
    volumes:
      # Mount the project directory for analysis - change HOST_PROJECT_PATH to your desired directory
      # Use .env file or set environment variable HOST_PROJECT_PATH
      - ${HOST_PROJECT_PATH:-C:\Users\hakim\Desktop}:/app/projects
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      # Container path where projects will be mounted
      - CONTAINER_PROJECT_PATH=/app/projects
    networks:
      - yaml-parser-network
    restart: unless-stopped
    # Health check to ensure backend is ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: bdutucu/yaml-parser-frontend:latest
    container_name: yaml-parser-frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - yaml-parser-network
    restart: unless-stopped
    # Health check for frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  yaml-parser-network:
    driver: bridge

volumes:
  uploads:
    driver: local
