name: yaml-parser
services:
  backend:
    image: bdutucu/yaml-parser-backend:v1.1
    container_name: yaml-parser-backend
    ports:
      - "5000:5000"
    volumes:
      # IMPORTANT: Change this path to your project directory
      # Windows example: C:\Users\username\Desktop\my-projects:/app/projects
      # Linux/Mac example: /home/username/projects:/app/projects
      #change user
      - C:\Users\hakim\Desktop:/app/projects
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - yaml-parser-network
    restart: unless-stopped

  frontend:
    image: bdutucu/yaml-parser-frontend:v1.1
    container_name: yaml-parser-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yaml-parser-network
    restart: unless-stopped

networks:
  yaml-parser-network:
    driver: bridge
